### ISSUE TITLE
Issue In Compiling 

### ISSUE THREAD

**Issue by WinterIsCommin** [cocomelonc/peekaboo#2]
Run the script with the command line provided, it printed "successfully compiled :)", but i could not find the output dll file. 
The following error is seen: 
peekaboo-enc.cpp:32:33: error: ‘s_32’ was not declared in this scope; did you mean ‘s_k32’?
   32 | unsigned int s_k32_len = sizeof(s_32);
      |                                 ^~~~
      |                                 s_k32
peekaboo-enc.cpp: In function ‘BOOL AuXNgXcSyyJYjErneID()’:
<img width="949" alt="Capture" src="https://user-images.githubusercontent.com/58075390/183246397-08377ddb-bce7-4532-8a3d-f26264645b00.PNG">

**Comment by cocomelonc** [comment]
Sorry it's just misprint in my code. https://github.com/cocomelonc/peekaboo/commit/878a8bc84ab33ca453c54478eafd599f6e7cf98a

**Comment by yairdabach1991** [comment]
where is outpout dll file?
